#!/usr/bin/env python

import sys
import csv
from jinja2 import Template
import StringIO
import pprint

def UnicodeDictReader(utf8_data, **kwargs):
    csv_reader = csv.DictReader(utf8_data, **kwargs)
    for row in csv_reader:
        yield dict([(k,v) for (k,v) in [(key, unicode(value, 'utf-8')) for key, value in row.iteritems()] if v.replace(' ', '')])

if __name__ == '__main__' :
	template = Template(open('tmpl.txt').read())

	rows = list(UnicodeDictReader(open(sys.argv[1])))
	
	title = sys.argv[1].split('/')[-1].split('.')[0]
	
	ctx = {
		'title' : title,
		'rows' : rows
	}

	html = template.render(**ctx)
	fh = open(sys.argv[2], 'w')
	fh.write(html.encode('utf-8'))
	fh.close()
